In [6]:
example_list = [1,2,3]
print(example_list)
example_collection = (1,[3,4,5],3)  
example_collection[1].append(5)
print(example_collection)
example_set = set([1,2,3,3,3,4])
print(example_set)

[1, 2, 3]
(1, [3, 4, 5, 5], 3)
{1, 2, 3, 4}

In [28]:
import pandas as pd

df = pd.DataFrame({
    'user_id' : [1,2,5],
    'name' : ['Michał','Anna','Adam'],
    'status' : [True, True, False]
})

# print(df)
# print(df.shape)
# print(df.info())
# print(df[{"status", "name"}])
# print(df.iloc[0:2])
# print(df.iloc[5,0])
# print("Adam", df[df.name == 'Adam'])
print(df)
# df[df.status.unique()]

   user_id    name  status
0        1  Michał    True
1        2    Anna    True
2        5    Adam   False

ValueError: ignored

In [35]:
import seaborn as sns

titanic_df = sns.load_dataset('titanic')
print(titanic_df)
print(titanic_df.columns)
print('all', titanic_df.isna().sum().sum())
print('deck', titanic_df['deck'].isna().sum())

     survived  pclass     sex   age  ...  deck  embark_town  alive  alone
0           0       3    male  22.0  ...   NaN  Southampton     no  False
1           1       1  female  38.0  ...     C    Cherbourg    yes  False
2           1       3  female  26.0  ...   NaN  Southampton    yes   True
3           1       1  female  35.0  ...     C  Southampton    yes  False
4           0       3    male  35.0  ...   NaN  Southampton     no   True
..        ...     ...     ...   ...  ...   ...          ...    ...    ...
886         0       2    male  27.0  ...   NaN  Southampton     no   True
887         1       1  female  19.0  ...     B  Southampton    yes   True
888         0       3  female   NaN  ...   NaN  Southampton     no  False
889         1       1    male  26.0  ...     C    Cherbourg    yes   True
890         0       3    male  32.0  ...   NaN   Queenstown     no   True

[891 rows x 15 columns]
Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')
all 869
deck 688

In [45]:
url = 'https://api.github.com/repos/MikiKru/p2'
github_df = pd.read_json(url, lines=True)
print(github_df.shape)
print(github_df.columns)
print(github_df.head(1))
print(github_df['private'])
print(github_df['language'])

(1, 76)
Index(['id', 'node_id', 'name', 'full_name', 'private', 'owner', 'html_url',
       'description', 'fork', 'url', 'forks_url', 'keys_url',
       'collaborators_url', 'teams_url', 'hooks_url', 'issue_events_url',
       'events_url', 'assignees_url', 'branches_url', 'tags_url', 'blobs_url',
       'git_tags_url', 'git_refs_url', 'trees_url', 'statuses_url',
       'languages_url', 'stargazers_url', 'contributors_url',
       'subscribers_url', 'subscription_url', 'commits_url', 'git_commits_url',
       'comments_url', 'issue_comment_url', 'contents_url', 'compare_url',
       'merges_url', 'archive_url', 'downloads_url', 'issues_url', 'pulls_url',
       'milestones_url', 'notifications_url', 'labels_url', 'releases_url',
       'deployments_url', 'created_at', 'updated_at', 'pushed_at', 'git_url',
       'ssh_url', 'clone_url', 'svn_url', 'homepage', 'size',
       'stargazers_count', 'watchers_count', 'language', 'has_issues',
       'has_projects', 'has_downloads', 'has_wiki', 'has_pages', 'forks_count',
       'mirror_url', 'archived', 'disabled', 'open_issues_count', 'license',
       'forks', 'open_issues', 'watchers', 'default_branch',
       'temp_clone_token', 'network_count', 'subscribers_count'],
      dtype='object')
          id  ... subscribers_count
0  344788815  ...                 1

[1 rows x 76 columns]
0    False
Name: private, dtype: bool
0    Java
Name: language, dtype: object

In [59]:
import requests
from bs4 import BeautifulSoup

data = requests.get('https://pogoda.interia.pl/prognoza-dlugoterminowa-bydgoszcz,cId,2942339')
# print(data.text)
html = BeautifulSoup(data.content, 'html.parser')
class_name = 'weather-currently-temp-strict'
temperature = html.find("div", attrs={'class' : class_name})
type(temperature)
print(str(temperature).replace('<div class="weather-currently-temp-strict">',"").replace("</div>",""))

-2°C